### ISSUE TITLE
Command-based extensibility

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/rhosts#3]
### Background 

See [Extensible Architecture Discussion](https://github.com/StevenBlack/rhosts/wiki/Extensible-Architecture-Discussion) in the wiki.

ATM the repo is named `rhosts` which isn't great; so `rhosts` is a placeholder for now.

- [ ] Come up with a better name than `rhosts`

# Roadmap

## Things to do

- [x] #4
- [ ] `rhosts.json` for userland config overrides

## Commands to implement

- [ ] `rhosts fetch` refreshes cached data in `./data` and `./extensions` subfolders
- [ ] `rhosts init` an alias for `rhosts fetch` but with helpers
- [ ] `rhosts build` assembles all the amalgamated versions of hosts
- [ ] `rhosts update` executes a `fetch` and `build`
- [ ] `rhosts upgrade` copies latest to `/etc/hosts` file (or specific OS equivalent)
- [ ] `rhosts compare` compares two hosts files
- [ ] `rhosts contribution` to analyze the contribution of an existing or potential hosts source

These nominally come "for free" with `clap` but they deserve some thought

- [x] `rhosts help` displays help
- [x] `rhosts version` echos the current version of `rhosts`
